name: "${project.name}"
author: "${author}"
website: "${project.url}"
description: "${project.description}"
main: "${bukkitMainClass}"
version: "${version}"
api-version: "1.13"
depend: [${dependencies}]
softdepend: [ Vault, Minepacks, MinePacks, MVdWPlaceholderAPI, PlaceholderAPI, SkillAPI, mcMMO, Multiverse-Core ${soft-dependencies} ]
